version: '3'

services:
  dev:
    container_name: comercial-data-collection-dev
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - '8888:8080'

  prod:
    container_name: comercial-dash-prod
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - '8888:8080'
      




